#!/usr/bin/env python3
"""Documentation generator for agent-infra-hub.

Derives living documentation from source-of-truth artifacts:

  - tools/agent_kb.py  → CLI reference (argparse introspection)
  - catalog.json       → resource path validation
  - 09-agent-infra-catalog/catalog.yaml → candidate repo ↔ filesystem audit
  - All *.md           → cross-link validation

Outputs land under docs/_generated/ and docs/reference/. The aim is that
whenever code (CLI signatures, file paths, catalog entries) changes,
`make docs` regenerates derived docs so committed docs never drift.

Usage:
  python tools/docs_gen.py all          # regenerate every derived doc
  python tools/docs_gen.py cli          # CLI reference only
  python tools/docs_gen.py links        # markdown link audit only
  python tools/docs_gen.py catalog      # catalog ↔ filesystem audit only
  python tools/docs_gen.py check        # regenerate to tempdir, diff vs committed (CI)

Standard library only — no external deps required.
"""

from __future__ import annotations

import argparse
import importlib.util
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from contextlib import redirect_stdout
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS = REPO_ROOT / "docs"
GENERATED = DOCS / "_generated"
REFERENCE = DOCS / "reference"

WARNING_BANNER = (
    "<!-- AUTO-GENERATED by tools/docs_gen.py — DO NOT EDIT BY HAND. "
    "Run `make docs` to regenerate. -->\n"
)

# Directories to skip when scanning markdown links.
SKIP_DIRS = {
    ".git",
    "node_modules",
    "data",
    "__pycache__",
    ".venv",
    "venv",
    "dist",
    "build",
    # Third-party clones documented separately; their internal cross-links
    # are not our concern.
    "09-agent-infra-catalog",
}

# Specific path prefixes (relative to REPO_ROOT) to skip — typically verbatim
# copies of upstream documentation that contain external link conventions
# (absolute /en/docs/... paths, sibling files we don't own).
SKIP_PATH_PREFIXES = (
    "skill-research/04-writing-guide/anthropic-best-practices.md",
    "skill-research/05-examples/",
)


def _vendored_roots() -> set[Path]:
    """Auto-detect vendored third-party clones (directories containing .git)."""
    roots: set[Path] = set()
    repo_git = REPO_ROOT / ".git"
    for git_dir in REPO_ROOT.rglob(".git"):
        if not git_dir.is_dir():
            continue
        if git_dir == repo_git:
            continue
        roots.add(git_dir.parent)
    return roots


# ---------------------------------------------------------------------------
# CLI reference generation
# ---------------------------------------------------------------------------

def _load_agent_kb_module():
    spec = importlib.util.spec_from_file_location(
        "agent_kb_module", REPO_ROOT / "tools" / "agent_kb.py"
    )
    module = importlib.util.module_from_spec(spec)
    sys.modules["agent_kb_module"] = module
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    return module


def _format_action(action: argparse.Action) -> dict[str, Any]:
    return {
        "option_strings": list(action.option_strings),
        "dest": action.dest,
        "nargs": action.nargs,
        "type": getattr(action.type, "__name__", str(action.type)) if action.type else None,
        "default": _json_safe(action.default),
        "choices": list(action.choices) if action.choices else None,
        "required": action.required,
        "help": action.help or "",
        "positional": not action.option_strings,
    }


def _json_safe(value: Any) -> Any:
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)


def _walk_subparsers(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    out: dict[str, argparse.ArgumentParser] = {}
    for action in parser._actions:  # noqa: SLF001
        if isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            for name, sp in action.choices.items():
                out[name] = sp
    return out


def _help_text(parser: argparse.ArgumentParser) -> str:
    buf = io.StringIO()
    with redirect_stdout(buf):
        parser.print_help()
    return buf.getvalue()


def generate_cli_reference() -> list[Path]:
    module = _load_agent_kb_module()
    # `parse_args` builds the parser; we need the parser itself, so reconstruct.
    # Reuse parse_args without invoking parse: it builds inside the function.
    # Simplest approach: monkey-patch sys.argv won't work because parse_args is
    # called inside. Instead, replicate the structure by introspecting the
    # function's bytecode is overkill — call parse_args(["--help"]) and catch
    # SystemExit while capturing the parser via instrumentation.
    parser = _build_agent_kb_parser(module)

    subparsers = _walk_subparsers(parser)

    spec_actions = [_format_action(a) for a in parser._actions  # noqa: SLF001
                    if not isinstance(a, argparse._SubParsersAction)]  # noqa: SLF001
    spec: dict[str, Any] = {
        "program": "agent_kb.py",
        "description": parser.description,
        "global_options": spec_actions,
        "subcommands": {},
    }
    for name, sp in subparsers.items():
        spec["subcommands"][name] = {
            "help": _subparser_help(parser, name),
            "options": [
                _format_action(a) for a in sp._actions  # noqa: SLF001
                if not isinstance(a, argparse._SubParsersAction)  # noqa: SLF001
            ],
        }

    GENERATED.mkdir(parents=True, exist_ok=True)
    REFERENCE.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    # cli-signatures.json (machine readable)
    sig_path = GENERATED / "cli-signatures.json"
    sig_path.write_text(json.dumps(spec, indent=2, ensure_ascii=False) + "\n",
                        encoding="utf-8")
    written.append(sig_path)

    # cli-help.md (raw --help output of every subcommand)
    help_md = [
        WARNING_BANNER,
        "# agent_kb.py — Raw `--help` Output",
        "",
        f"_Source: `tools/agent_kb.py` · Regenerated by `make docs` ({_utc_today()})_",
        "",
        "## Top-level",
        "",
        "```",
        _help_text(parser).rstrip(),
        "```",
        "",
    ]
    for name, sp in subparsers.items():
        help_md += [
            f"## `{name}`",
            "",
            "```",
            _help_text(sp).rstrip(),
            "```",
            "",
        ]
    help_path = GENERATED / "cli-help.md"
    help_path.write_text("\n".join(help_md), encoding="utf-8")
    written.append(help_path)

    # reference/agent_kb_cli.md — narrative human-readable reference
    ref_lines = [
        WARNING_BANNER,
        "# `agent_kb.py` CLI Reference",
        "",
        f"_Auto-generated from `tools/agent_kb.py` argparse introspection. "
        f"Regenerated by `make docs` ({_utc_today()})._",
        "",
        f"**Description:** {parser.description}",
        "",
        "## Invocation",
        "",
        "```bash",
        "python tools/agent_kb.py [--db DB] <command> [options]",
        "```",
        "",
        "## Global Options",
        "",
        _options_table(spec_actions),
        "",
        "## Commands",
        "",
        "| Command | Purpose |",
        "|---------|---------|",
    ]
    for name, sub in spec["subcommands"].items():
        ref_lines.append(f"| [`{name}`](#{name}) | {sub['help']} |")
    ref_lines.append("")
    for name, sub in spec["subcommands"].items():
        ref_lines += [
            f"### `{name}`",
            "",
            f"{sub['help']}",
            "",
            _options_table(sub["options"]),
            "",
        ]
    ref_path = REFERENCE / "agent_kb_cli.md"
    ref_path.write_text("\n".join(ref_lines), encoding="utf-8")
    written.append(ref_path)

    return written


def _build_agent_kb_parser(module) -> argparse.ArgumentParser:
    """Reconstruct the parser without invoking parse on real argv.

    The module's `parse_args` builds the parser and then calls
    `parser.parse_args(argv)`. We invoke it with `["--help"]` would
    sys.exit. So we monkey-patch ArgumentParser.parse_args temporarily to
    capture the parser and return early.
    """
    captured: dict[str, argparse.ArgumentParser] = {}

    original_parse = argparse.ArgumentParser.parse_args

    def capturing_parse(self, args=None, namespace=None):  # type: ignore[override]
        captured["parser"] = self
        # Return an empty namespace so module doesn't crash; caller discards.
        return argparse.Namespace()

    argparse.ArgumentParser.parse_args = capturing_parse  # type: ignore[assignment]
    try:
        module.parse_args([])
    finally:
        argparse.ArgumentParser.parse_args = original_parse  # type: ignore[assignment]

    if "parser" not in captured:
        raise RuntimeError("Could not capture argparse parser from agent_kb.py")
    return captured["parser"]


def _subparser_help(parser: argparse.ArgumentParser, name: str) -> str:
    for action in parser._actions:  # noqa: SLF001
        if isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            for choice_action in action._choices_actions:  # noqa: SLF001
                if choice_action.dest == name:
                    return choice_action.help or ""
    return ""


def _options_table(actions: list[dict[str, Any]]) -> str:
    if not actions:
        return "_(no options)_"
    rows = ["| Flag | Type | Default | Description |",
            "|------|------|---------|-------------|"]
    for a in actions:
        if a["positional"]:
            flag = f"`{a['dest']}`"
        else:
            flag = ", ".join(f"`{s}`" for s in a["option_strings"])
        type_ = a["type"] or ("flag" if a["nargs"] == 0 else "str")
        default = "—" if a["default"] in (None, "") else f"`{a['default']}`"
        desc = a["help"].replace("|", "\\|")
        if a["choices"]:
            desc += f" Choices: {', '.join(f'`{c}`' for c in a['choices'])}."
        rows.append(f"| {flag} | `{type_}` | {default} | {desc} |")
    return "\n".join(rows)


# ---------------------------------------------------------------------------
# Markdown link audit
# ---------------------------------------------------------------------------

LINK_RE = re.compile(r"\[[^\]]+\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
CODE_SPAN_RE = re.compile(r"`[^`\n]*`")
FENCE_RE = re.compile(r"^\s*```")

def _iter_markdown_files() -> Iterable[Path]:
    vendored = _vendored_roots()
    for path in REPO_ROOT.rglob("*.md"):
        rel = path.relative_to(REPO_ROOT)
        rel_str = rel.as_posix()
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        if any(rel_str.startswith(p) for p in SKIP_PATH_PREFIXES):
            continue
        if any(parent in vendored for parent in path.parents):
            continue
        yield path


def audit_links() -> Path:
    broken: list[tuple[str, int, str]] = []
    scanned = 0
    link_count = 0
    for md in _iter_markdown_files():
        scanned += 1
        text = md.read_text(encoding="utf-8", errors="replace")
        in_fence = False
        for lineno, line in enumerate(text.splitlines(), start=1):
            if FENCE_RE.match(line):
                in_fence = not in_fence
                continue
            if in_fence:
                continue
            # Strip inline code spans before extracting links.
            stripped = CODE_SPAN_RE.sub("", line)
            for match in LINK_RE.finditer(stripped):
                target = match.group(1)
                link_count += 1
                if not _link_resolves(md, target):
                    broken.append((str(md.relative_to(REPO_ROOT)), lineno, target))

    GENERATED.mkdir(parents=True, exist_ok=True)
    out = [
        WARNING_BANNER,
        "# Markdown Link Audit",
        "",
        f"_Generated {_utc_today()} by `tools/docs_gen.py links`._",
        "",
        f"- Files scanned: **{scanned}**",
        f"- Links checked: **{link_count}**",
        f"- Broken: **{len(broken)}**",
        "",
    ]
    if broken:
        out += [
            "## Broken / Unresolved Links",
            "",
            "| File | Line | Target |",
            "|------|------|--------|",
        ]
        for file, line, target in broken:
            out.append(f"| `{file}` | {line} | `{target}` |")
    else:
        out.append("✅ All internal links resolve.")
    out.append("")
    path = GENERATED / "link-report.md"
    path.write_text("\n".join(out), encoding="utf-8")
    return path


def _link_resolves(source: Path, target: str) -> bool:
    if target.startswith(("http://", "https://", "mailto:", "tel:")):
        return True
    if target.startswith("#"):
        return True  # anchor-only — not validated
    # Strip query/fragment
    clean = target.split("#", 1)[0].split("?", 1)[0]
    if not clean:
        return True
    if clean.startswith("/"):
        candidate = REPO_ROOT / clean.lstrip("/")
    else:
        candidate = (source.parent / clean).resolve()
    try:
        candidate.relative_to(REPO_ROOT)
    except ValueError:
        # Outside the repo — accept (e.g., absolute /home/l/... references).
        return candidate.exists()
    return candidate.exists()


# ---------------------------------------------------------------------------
# Catalog ↔ filesystem audit
# ---------------------------------------------------------------------------

REPO_ENTRY_RE = re.compile(r"^\s*-\s+name:\s*(.+?)\s*$")


def audit_catalog() -> Path:
    issues: list[str] = []
    notes: list[str] = []

    # 1. catalog.json — every resource.path must exist (or be url).
    cj_path = REPO_ROOT / "catalog.json"
    catalog_json_resource_count = 0
    cj_missing: list[str] = []
    if cj_path.exists():
        data = json.loads(cj_path.read_text(encoding="utf-8"))
        for res in data.get("resources", []):
            catalog_json_resource_count += 1
            p = res.get("path")
            if not p:
                continue
            if not (REPO_ROOT / p).exists():
                cj_missing.append(f"{res.get('id', '?')} → {p}")
    else:
        notes.append("catalog.json not found at repo root.")

    # 2. catalog.yaml repositories — each `name` should correspond to a
    #    clone under 09-agent-infra-catalog/<category>/<basename>.
    cy_path = REPO_ROOT / "09-agent-infra-catalog" / "catalog.yaml"
    catalog_yaml_repos: list[str] = []
    cy_missing: list[str] = []
    if cy_path.exists():
        for line in cy_path.read_text(encoding="utf-8").splitlines():
            m = REPO_ENTRY_RE.match(line)
            if m:
                catalog_yaml_repos.append(m.group(1))
        for full in catalog_yaml_repos:
            basename = full.split("/")[-1]
            # find any directory ending in /basename inside 09-agent-infra-catalog
            matches = list((REPO_ROOT / "09-agent-infra-catalog").glob(f"*/{basename}"))
            if not matches:
                cy_missing.append(full)

    GENERATED.mkdir(parents=True, exist_ok=True)
    out = [
        WARNING_BANNER,
        "# Catalog ↔ Filesystem Audit",
        "",
        f"_Generated {_utc_today()} by `tools/docs_gen.py catalog`._",
        "",
        "## catalog.json",
        "",
        f"- Resources declared: **{catalog_json_resource_count}**",
        f"- Missing on disk: **{len(cj_missing)}**",
        "",
    ]
    if cj_missing:
        out += ["### Missing paths", ""]
        out += [f"- `{m}`" for m in cj_missing]
        out.append("")
    out += [
        "## 09-agent-infra-catalog/catalog.yaml",
        "",
        f"- Candidate repositories declared: **{len(catalog_yaml_repos)}**",
        f"- Not yet cloned locally: **{len(cy_missing)}**",
        "",
    ]
    if cy_missing:
        out += [
            "### Declared but not present on disk",
            "",
            "_(These are `metadata_first` entries — expected until promoted.)_",
            "",
        ]
        out += [f"- `{m}`" for m in cy_missing]
        out.append("")
    if notes:
        out += ["## Notes", ""] + [f"- {n}" for n in notes] + [""]

    path = GENERATED / "catalog-fs-report.md"
    path.write_text("\n".join(out), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _utc_today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _ensure_generated_readme() -> Path:
    GENERATED.mkdir(parents=True, exist_ok=True)
    path = GENERATED / "README.md"
    if not path.exists():
        path.write_text(
            WARNING_BANNER
            + "# `docs/_generated/` — Auto-Generated Reports\n\n"
            "All files in this directory are produced by `tools/docs_gen.py`.\n"
            "Do not hand-edit. Run `make docs` (or `python tools/docs_gen.py all`) to regenerate.\n\n"
            "| File | Source of truth | Producer |\n"
            "|------|-----------------|----------|\n"
            "| `cli-help.md` | `tools/agent_kb.py` argparse | `docs_gen.py cli` |\n"
            "| `cli-signatures.json` | `tools/agent_kb.py` argparse | `docs_gen.py cli` |\n"
            "| `link-report.md` | All repository `*.md` files | `docs_gen.py links` |\n"
            "| `catalog-fs-report.md` | `catalog.json` + `09-agent-infra-catalog/catalog.yaml` | `docs_gen.py catalog` |\n",
            encoding="utf-8",
        )
    return path


# ---------------------------------------------------------------------------
# Check mode (CI)
# ---------------------------------------------------------------------------

def check_in_place() -> int:
    """Run all generators in a temp scratch area and diff vs committed."""
    global GENERATED, REFERENCE
    original_generated = GENERATED
    original_reference = REFERENCE
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        GENERATED = tmp_path / "_generated"
        REFERENCE = tmp_path / "reference"
        generate_cli_reference()
        audit_links()
        audit_catalog()

        diff_failures: list[str] = []
        for src in GENERATED.rglob("*"):
            if not src.is_file():
                continue
            rel = src.relative_to(GENERATED)
            committed = original_generated / rel
            if not committed.exists() or committed.read_bytes() != src.read_bytes():
                diff_failures.append(str(original_generated / rel))
        for src in REFERENCE.rglob("*"):
            if not src.is_file():
                continue
            rel = src.relative_to(REFERENCE)
            committed = original_reference / rel
            if not committed.exists() or committed.read_bytes() != src.read_bytes():
                diff_failures.append(str(original_reference / rel))

    GENERATED = original_generated
    REFERENCE = original_reference

    if diff_failures:
        print("DOC DRIFT — the following committed docs are stale:", file=sys.stderr)
        for f in diff_failures:
            print(f"  - {f}", file=sys.stderr)
        print("Run `make docs` and commit the result.", file=sys.stderr)
        return 1
    print("✅ All generated docs are up to date.")
    return 0


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "task",
        choices=["all", "cli", "links", "catalog", "check"],
        help="Which generator to run.",
    )
    args = parser.parse_args(argv)

    if args.task == "check":
        return check_in_place()

    produced: list[Path] = []
    if args.task in ("all", "cli"):
        produced += generate_cli_reference()
    if args.task in ("all", "links"):
        produced.append(audit_links())
    if args.task in ("all", "catalog"):
        produced.append(audit_catalog())
    if args.task == "all":
        produced.append(_ensure_generated_readme())

    for p in produced:
        print(f"wrote {p.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
